export const MASTER_CHECKLIST = [
  { item: "1. Basic Info", subItem: "Resin", checkPoint: "Confirm resin type/grade/color/shrinkage", standard: "Must match 2D/CMF & supplier datasheet" },
  { item: "1. Basic Info", subItem: "Resin", checkPoint: "Common or new resin? Special requirement (UL/UV/RTI)", standard: "New resin requires justification & approval" },
  { item: "1. Basic Info", subItem: "Resin", checkPoint: "Shrinkage vs datasheet", standard: "Within TDS from Resin vendor" },
  { item: "1. Basic Info", subItem: "Tooling", checkPoint: "Cavities/runner match quotation", standard: "100% match quotation" },
  { item: "1. Basic Info", subItem: "Steel", checkPoint: "Steel selection for surface/tool life", standard: "suitable for surface finish & tool life (>300k shots typical)" },
  { item: "1. Basic Info", subItem: "Process", checkPoint: "Full process to make part", standard: "" },
  { item: "1. Basic Info", subItem: "Machine", checkPoint: "Machine size suitability", standard: "Within machine tonnage limit & same quotation" },
  { item: "1. Basic Info", subItem: "Cycle time", checkPoint: "Cycle time estimation", standard: "Based on cooling & thickness" },
  { item: "1. Basic Info", subItem: "Cost", checkPoint: "Optimization opportunity: machine, process, part combine", standard: "Cost/leadtime improvement identified" },
  { item: "2. Wall Thickness", subItem: "Design", checkPoint: "Uniform wall thickness", standard: "Thickness variation <30%" },
  { item: "2. Wall Thickness", subItem: "Design", checkPoint: "Avoid sudden thickness change", standard: "Use smooth transition/fillet" },
  { item: "2. Wall Thickness", subItem: "Risk", checkPoint: "Highlight stress risk", standard: "Must be reviewed with PDE/PLM" },
  { item: "2. Geometry", subItem: "Undercut", checkPoint: "Minimize undercut", standard: "Avoid if possible or use slider/lifter" },
  { item: "2. Geometry", subItem: "Feasibility", checkPoint: "Optimize geometry", standard: "Tooling feasible without risk" },
  { item: "2. Surface Finishing", subItem: "Cosmetic", checkPoint: "Meet cosmetic/function requirement", standard: "Per CMF/spec" },
  { item: "2. Surface Finishing", subItem: "Cost", checkPoint: "Avoid over-spec", standard: "No unnecessary high polish" },
  { item: "2. Surface Finishing", subItem: "Draft", checkPoint: "Draft for texture release", standard: "≥1° texture / ≥0.5° polished" },
  { item: "3. Machine", subItem: "Productivity", checkPoint: "Machine size suitability", standard: "Within machine tonnage limit" },
  { item: "3. Machine", subItem: "Cycle time", checkPoint: "Cycle time estimation", standard: "Based on cooling & thickness" },
  { item: "3. Runner/Gate", subItem: "Runner", checkPoint: "Hot vs cold runner selection", standard: "Optimized cost vs performance" },
  { item: "3. Runner/Gate", subItem: "Gate type", checkPoint: "Suitable for structure", standard: "No defect risk" },
  { item: "3. Runner/Gate", subItem: "Gate size", checkPoint: "Adequate size", standard: "50–80% wall thickness" },
  { item: "3. Runner/Gate", subItem: "Gate location", checkPoint: "Avoid cosmetic/critical area", standard: "No visual defect" },
  { item: "3. Runner/Gate", subItem: "Gate qty", checkPoint: "Sufficient for filling", standard: "No short shot" },
  { item: "4. Mold Flow", subItem: "Filling", checkPoint: "Filling balance, Gate impact", standard: "<10% variation between cavities" },
  { item: "4. Mold Flow", subItem: "Optimization", checkPoint: "Gate optimization", standard: "Optimized position/size" },
  { item: "4. Mold Flow", subItem: "Flow control", checkPoint: "Flow leader/restrictor", standard: "Used if needed" },
  { item: "4. Mold Flow", subItem: "Risk", checkPoint: "Weldline", standard: "Not at cosmetic/strength area" },
  { item: "4. Mold Flow", subItem: "Risk", checkPoint: "Air trap", standard: "No major air trap" },
  { item: "4. Mold Flow", subItem: "Risk", checkPoint: "Sink mark", standard: "Within acceptable level" },
  { item: "4. Mold Flow", subItem: "Risk", checkPoint: "Warpage", standard: "Within tolerance" },
  { item: "4. Mold Flow", subItem: "Risk", checkPoint: "Stress mark", standard: "No visible defect" },
  { item: "5. Parting Line", subItem: "PL", checkPoint: "PL location", standard: "Not on cosmetic/sealing surface" },
  { item: "5. Parting Line", subItem: "PL", checkPoint: "Straight PL preferred", standard: "Maximize straight line" },
  { item: "5. Parting Line", subItem: "PL", checkPoint: "Core side priority", standard: "Follow tooling standard" },
  { item: "5. Parting Line", subItem: "PL", checkPoint: "Mismatch", standard: "≤0.05mm cosmetic" },
  { item: "5. Parting Line", subItem: "PL", checkPoint: "Dimension control", standard: "Critical dim on one side" },
  { item: "5. Slider", subItem: "Structure", checkPoint: "Layout optimized", standard: "No interference" },
  { item: "5. Slider", subItem: "Strength", checkPoint: "Structure strength", standard: "Safety factor >2" },
  { item: "5. Slider", subItem: "Cooling", checkPoint: "Cooling for big slider", standard: "Required if large size" },
  { item: "5. Lifter", subItem: "Function", checkPoint: "No assembly interference", standard: "No stuck/step issue" },
  { item: "5. Lifter", subItem: "Strength", checkPoint: "Lifetime durability", standard: "Meets tool life" },
  { item: "5. Insert", subItem: "Design", checkPoint: "Insert for fragile area", standard: "Required" },
  { item: "5. Insert", subItem: "Precision", checkPoint: "Insert for critical dimension", standard: "Required" },
  { item: "5. Insert", subItem: "Risk", checkPoint: "Insert for thin rib", standard: "Recommended" },
  { item: "5. Insert", subItem: "Cosmetic", checkPoint: "Avoid insert line", standard: "Not on cosmetic surface" },
  { item: "5. Insert", subItem: "Flexibility", checkPoint: "Exchangeable insert", standard: "Optional for variants" },
  { item: "5. Ejector", subItem: "Ejection", checkPoint: "Sufficient ejector layout", standard: "No deformation" },
  { item: "5. Ejector", subItem: "Type", checkPoint: "Ejector type selection", standard: "Pin/blade/sleeve as needed" },
  { item: "5. Ejector", subItem: "Cosmetic", checkPoint: "Avoid ejector mark", standard: "No mark on cosmetic" },
  { item: "5. Cooling", subItem: "Coverage", checkPoint: "Cooling coverage", standard: "Uniform cooling ΔT <10°C" },
  { item: "5. Cooling", subItem: "Distance", checkPoint: "Part to waterline", standard: "≥1.5x channel diameter" },
  { item: "5. Cooling", subItem: "Safety", checkPoint: "Waterline to tool edge", standard: "Safe thickness maintained" },
  { item: "5. Cooling", subItem: "Extra", checkPoint: "Cooling for sprue/runner", standard: "If possible" },
  { item: "5. Venting", subItem: "Vent", checkPoint: "Vent location", standard: "At end of fill" },
  { item: "5. Venting", subItem: "Depth", checkPoint: "Vent depth", standard: "0.01–0.03mm (material dependent)" },
  { item: "5. Venting", subItem: "Result", checkPoint: "Avoid defect", standard: "No burn/air trap" },
  { item: "6. Heat Staking", subItem: "Strength", checkPoint: "Structure strength", standard: "No crack/loose/ balance heatstack position" },
  { item: "6. Heat Staking", subItem: "Space", checkPoint: "Dome space, No interference if ofset 0.5mm", standard: "Enough clearance after heatstack" },
  { item: "6. Tool Safety", subItem: "Safety", checkPoint: "Avoid sharp edge", standard: "Chamfer required" },
  { item: "7. Tolerance", subItem: "Dimension", checkPoint: "Match assembly/function", standard: "Measureable" },
  { item: "7. Tolerance", subItem: "Tight", checkPoint: "Avoid over tight", standard: "Compare to general tolerance" },
  { item: "7. Tolerance", subItem: "screw size", checkPoint: "Screw size must follow standard", standard: "Standard" },
  { item: "8. Handling", subItem: "Pick-up", checkPoint: "No scratch/deformation", standard: "Safe handling" },
  { item: "8. Cosmetic", subItem: "Marks", checkPoint: "Avoid marks", standard: "Hidden if unavoidable" },
  { item: "9. Marking", subItem: "Date/PN/Rev", checkPoint: "Correct marking", standard: "Follow Drawing & size readable" },
  { item: "9. Marking", subItem: "Space", checkPoint: "Engraving space", standard: "Not interfere when assembly" }
];
